### ISSUE TITLE
1.19.2 | Question

### ISSUE THREAD

**Issue by OdontoZoom** [Ultimating/UltraColor#10]
Minecraft Version 1.18.2 - 1.19.3 | This questions are about Gradient Lore.

![image](https://user-images.githubusercontent.com/87169363/221016744-be621378-50ca-4e4a-8184-79ff495b89ab.png)

Is it possible to show a preview of the player's own name in gradient lore? or maybe, is there some placeholder to show that?

![image](https://user-images.githubusercontent.com/87169363/221016943-e7b59dcd-aed9-4935-90e4-7f49ce9ef3cc.png)

Does gradient lore allows placeholder from other plugins?

![image](https://user-images.githubusercontent.com/87169363/221017028-6cf94e9b-3344-4ac0-9408-68cadc1d2e06.png)

Thank you.

**Comment by Ultimating** [comment]
The closest thing I can give you is the {color_preview} placeholder.

This placeholder can be used in color selection menus, including gradient selection. What it'll do is replace the placeholder with "this" and colorize it with the color you're previewing.

You should be able to use it in the Menu_Lore section in the first image you attached. Let me know how it goes!
