### ISSUE TITLE
Command Reset

### ISSUE THREAD

**Issue by flavioope** [Ultimating/UltraColor#3]
Hello! me again, now my suggestion is instead of /ucolor resetcolor <player> not remove all your chat colors, name.
You could create the command something like `/ucolor reset <chat/name> <player> <color> <format>(Optional)` 😁

1) Well, I think some of us are configurators, so if we wanted to make a menu apart from the one that the plugin already has, it would be nice to be able to execute that command from the console and not just from the player. (Not if I explain well)

2)

3)  None more, I hope this gets added, even though the plugin doesn't get updates constantly anymore, it's still a very good plugin.

**Comment by Ultimating** [comment]
Hello again!

I've gone ahead and implemented this suggestion as it was minor and can see it as a useful improvement! I'll post a new version on GitHub and Spigot in the next update, but just in case you can't wait that long, I've made a modified jar of the current version with your suggestion.

You can download it [here](https://ufile.io/vv1zpf9c)!

When you do update, there is one manual modification you need to do in your message file. Simply go in there, find **Player_Reset_Color_Command_Success** (~line 695), and add **%type%** in the string of text. This is a placeholder that tells which type of color has been reset (either chat or name). It can be anywhere in the message but place it where it makes the most sense.

Enjoy and let me know how it works!

**Comment by flavioope** [comment]
Thank you very much for adding this, I really appreciate it, excellent plugin!1

**Comment by Ultimating** [comment]
I should specify that the command to reset colors is still the same, but now there's an argument to specify either resetting the chat or name colors of a player. So now the reset color command is `/ucolor resetcolor <chat/name> <player>`

**Comment by flavioope** [comment]
Yes, again thank you very much for adding it I really appreciate it 10/10

**Comment by Ultimating** [comment]
Of course! I'll now be closing this as this suggestion is done. You'll get a shoutout when this update goes on Spigot/GitHub! :)
