### ISSUE TITLE
1.8 | Question

### ISSUE THREAD

**Issue by flavioope** [Ultimating/UltraColor#4]
I have a question, is there a variable to obtain the color that the player has selected?
for example `%ultracolor_chat_selected_<color>%` and the same for the name `%ultracolor_name_selected_<color>%`

**Comment by Ultimating** [comment]
Hello!

Yes, there is! These PlaceholderAPI placeholders registered with the plugin may help you:
- `%ucolor_chat_color_name%` - Returns the player's selected chat color name (Use this placeholder to show what chat color a player has, for example, in a scoreboard or tab).
- `%ucolor_name_color_name%` - Returns the player's selected name color name (Use this placeholder to show what name color a player has, for example, in a scoreboard or tab).

For a full list of placeholders, visit the main plugin page [here ](https://www.spigotmc.org/resources/ultracolor-deprecated.85332/)and scroll down to the spoiler "PlaceholderAPI Placeholders". I may probably make a Wiki page for these to make them more obvious.

**Comment by flavioope** [comment]
Ok thank you very much can I leave another suggestion?

**Comment by Ultimating** [comment]
You can leave your suggestion here if you would like. It's great to recycle!

**Comment by flavioope** [comment]
> You can leave your suggestion here if you would like. It's great to recycle!

Ok look I don't know if it is possible to put certain items to be able to execute commands.

Example:
```
   Back_Button:
     Item: PLAYER_HEAD:https://textures.minecraft.net/texture/82388cd43df2a5ec4168ff7cb33a5a6d53475c3c1553fee7cab7242a6d193200
     Commands:
      - dm open menu %player_name%```
 
If nothing is put in the commands section, it just sends you to the main menu of the plugin

**Comment by Ultimating** [comment]
Hmm. Well, if I would implement this, it would probably go in your messages file. However, the file itself is quite long as it is.

From my understanding, you want to completely avoid all of this plugin's menus, but correct me if I'm wrong. Regardless though, I don't see a major need for this suggestion sadly. However, you could use plugins like MyCommand to create custom commands that could run other commands.

**Comment by flavioope** [comment]
I mean that I can execute commands on a button, for example on the back button, I want it to go to a deluxemenus menu, I don't know if I'm understanding

**Comment by flavioope** [comment]
What happens is that I am making a profile menu and I want that when I click back on the button, it sends that menu to the same to open the chat colors and name colors menu for example

`/color name` > Open the color menu for the name
`/color chat` > Open the color menu for the chat

**Comment by flavioope** [comment]
But if you can't add it, no problem.

**Comment by Ultimating** [comment]
`/namecolor` and `/chatcolor` also exist in the plugin. /namecolor opens the name color menu and /chatcolor opens the chat color menu.

Not being able to add this suggestion isn't the reason entirely. I also feel this would make the menu system complicated for those who would rather use the plugin's built-in menus. Especially for a deprecated plugin, complexity is something I'm avoiding.

I appreciate your understanding! Closing this now having the question and suggestion answered.
