### ISSUE TITLE
1.19 FoException Sending database query must be called async

### ISSUE THREAD

**Issue by ItzRonaldMLG** [Ultimating/UltraColor#6]
Server version: 1.19 Paper
UltraColor version: 1.5.9

When the server restarts there will be an error and the settings from the player dont save. (the nickname doesnt save, color does..)
Error in the error log: https://pastebin.com/RUBRXkUc
  
Also, maybe an option to cancel the hex color selection process with typing cancel in chat?

**Comment by Ultimating** [comment]
I've seen this happen on my other private plugins, but I keep forgetting to report this.

I'll report this to see if I can get any help fixing this. But there's nothing I can do to fix this alone. 

About your purposed option, it's already implemented. However, I haven't made it clear there that it's a valid option for each prompt. I do plan to modify the prompt system very similarly like how I did with the gradients (not showing the format prompt if formats are disabled and the placeholder to display format options). So with that in mind, I'll make note of this too.

**Tip:** Just about every prompt in this plugin has "cancel" as a prompt canceller word thanks to the library I use for prompts. So when interacting with prompts, it's safe to assume that you can use cancel in them, unless I specify something different.

**Comment by Ultimating** [comment]
**Update:** @ItzRonaldMLG, it seems I have gotten the issue fixed. Can you please try the attached jar to see if it's fixed on your end? If all is well, I'll push an update with this patch and another improvement!

Thanks!

[Test Jar](https://ufile.io/vp9c9gih)

**Comment by ItzRonaldMLG** [comment]
> **Update:** @ItzRonaldMLG, it seems I have gotten the issue fixed. Can you please try the attached jar to see if it's fixed on your end? If all is well, I'll push an update with this patch and another improvement!
> 
> Thanks!
> 
> [Test Jar](https://ufile.io/vp9c9gih)

The issue of the nickname reset is fixed, but i get another error this time: https://pastebin.com/EpSU0FnH

**Comment by Ultimating** [comment]
@ItzRonaldMLG Hmm, interesting. I didn't see that from my side when I tested.

Could you set up a fresh test server, with a fresh UltraColor jar and a fresh database and see if it occurs with that? Also, when does this error occur? From what I can tell, it seems to be when a player logs in, but I could be wrong.

Lastly, the exception asks you to check the error.log file and provide me with at least the content of it.

**Comment by ItzRonaldMLG** [comment]
Hello, i got it on my test server and deleted the files.
First it worked good, then i only connected it to my MySQL database (same database as always) and it created the error.
Seems to be something with the MySQL database?
Yes, it s on joining the server.
Error doesnt go away if i reset my colors and take an other color.
https://pastebin.com/4mrxQc8q

**Comment by UltimateGamer200** [comment]
So the error doesn't occur on a freshly created database or did you not create a database for your test side? If I didn't specify for you to try that, I'm sorry.

If you didn't do a fresh database too for your test server, I would reset your UltraColor folder, and this time, have the plugin connect to that test database, and see if the error occurs.

If the test database doesn't give the error, then this probably may have to do with your database.

> Hello, i got it on my test server and deleted the files. First it worked good, then i only connected it to my MySQL database (same database as always) and it created the error. Seems to be something with the MySQL database? Yes, it s on joining the server. Error doesnt go away if i reset my colors and take an other color. https://pastebin.com/4mrxQc8q

**Comment by Ultimating** [comment]
@ItzRonaldMLG

So the error doesn't occur on a freshly created database or did you not create a database for your test side?

If you didn't do a fresh database too for your test server, I would regenerate your UltraColor folder (including the data.db file), and this time, have the plugin connect to that test database, and see if the error occurs.

If the test database doesn't give the error, then this probably may have to do with your database, specifically.

**Comment by ItzRonaldMLG** [comment]
I think something was incompatible between the MySQL and data.db Maybe something changed in the one or other?
I deleted the MySQL and the data.db both before i start the server and its fixed.. It seems like if you leave 1 of them in and delete the other, the error will still show.

**Comment by Ultimating** [comment]
Hm, interesting.

At this point, I can't replicate the issue, and because of that, I can't provide a fix for you.

The only real solution I can give is to backup your database and UltraColor folder and do a reset of player data on the database and data.db file. If you do have the capabilities to back up your MySQL database, I highly encourage you to do so. 

I'm sorry that this is the only thing I can give to you.

**Comment by sovtec** [comment]
Alltho this is closed i want to add a small comment.

Perhaps there is issues with mysql because you have a outdated or not supported version of php/mysql?
