### ISSUE TITLE
%ucolor_player_select% Possibility

### ISSUE THREAD

**Issue by flavioope** [Ultimating/UltraColor#8]
I have a query is it possible to create a variable to know if the player has to select the color for example: %ucolor_player_select_<color>% is it possible that it can be added?

**Comment by Ultimating** [comment]
So you're asking if it's possible to create a placeholder that shows if a player can select a certain color? Or something else?

Eg: "&dCan select color?: &f%ucolor_player_select" (would return yes or no)

**Comment by Ultimating** [comment]
@flavioope Closed due to inactivity. If you want to leave an answer to my question, please leave a response back.
